package coreJava.variable;

public class AwsEc2BillingCalculator {
	
	/*
	 * STATIC VARIABLES
	*/
	static String cloudProvider = "AWS";
	static String currency = "INR";
	static int gstPercentage = 18;
	static String supportPlan = "BUSINESS";
	
	/*
	 * INSTANCE VARIABLES
	*/
	String instanceId;
	String instanceName;
	String ownerName;
	CloudRegion cloudRegion;
	InstanceType instanceType;
	OperatingSystem operatingSystem;
	float runningHours;
	double hourlyCost;
	boolean elasticIpEnabled;
	
	public static void main(String[] args) {
		
		AwsEc2BillingCalculator ec2 = new AwsEc2BillingCalculator();
		ec2.instanceId = args[0];
		ec2.instanceName = args[1];
		ec2.ownerName = args[2];
		ec2.cloudRegion = CloudRegion.valueOf(args[3]);
		ec2.instanceType = InstanceType.valueOf(args[4]);
		ec2.operatingSystem = OperatingSystem.valueOf(args[5]) ;
		ec2.runningHours = Float.parseFloat(args[6]);
		ec2.hourlyCost = Double.parseDouble(args[7]);
		ec2.elasticIpEnabled = Boolean.parseBoolean(args[8]);
		
		/*
		 * LOCAL VARIABLES
		 */
		
		double monthlyBill = ec2.runningHours * ec2.hourlyCost;
		double gst = monthlyBill * gstPercentage / 100.00;
		double finalBill = monthlyBill + gst;
		
		System.out.println(
					"===========================================" +
					"\nAWS EC2 BILLING REPORT" +
					"\n===========================================" +
					"\nCloud Provider: " + AwsEc2BillingCalculator.cloudProvider +
					"\nSupport Plan: " + AwsEc2BillingCalculator.supportPlan +
					"\nCurrency: " + AwsEc2BillingCalculator.currency +
					"\nGST Percentage: " + AwsEc2BillingCalculator.gstPercentage +
					"\n\nINSTANCE INFORMATION" +
					"\n-------------------------------------------" +
					"\nInstance ID: " + ec2.instanceId +
					"\nInstance Name: " + ec2.instanceName +
					"\nOwner Name: " + ec2.ownerName +
					"\n\nRegion: " + ec2.cloudRegion +
					"\nInstance Type: " + ec2.instanceType +
					"\nOperating System: " + ec2.operatingSystem +
					"\n\nRunning Hours: " + ec2.runningHours +
					"\nHourly Cost: " + ec2.hourlyCost +
					"\nElastic IP Enabled: " + ec2.elasticIpEnabled +
					"\n\nBILLING SUMMARY" +
					"\n-------------------------------------------" +
					"\nMonthly Compute Cost: ₹" + monthlyBill +
					"\nGST (18%): " + gst +
					"\n--------------------------------" +
					"\nTOTAL PAYABLE: " + finalBill +
					"\n===========================================" +
					"\nGENERATED BY CLOUDOPS BILLING SYSTEM v1.0" +
					"\n==========================================="					
				);
	}
}
